theme: jekyll-theme-cayman

gem "github-pages", group: :jekyll_plugins

title: ['C语言课程']

description: ['知识点']

show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

